### ISSUE TITLE
Sugestão Adicionar parquets de volumes máximo e mínimo das usinas

### ISSUE THREAD

**Issue by davidAlexander08** [rjmalves/sintetizador-newave#15]

**Comment by rjmalves** [comment]
Vou adicionar uma milestone para a release 2.0.0 do sintetizador, onde os dados de operação vou conter, além da coluna "valor", as colunas "limiteInferior" e "limiteSuperior", por estágio. Nesse caso, a síntese de volume armazenado por usina já traria esta informação.
