### ISSUE TITLE
Problema na leitura de EARM_REE_MES

### ISSUE THREAD

**Issue by lkhenayfis** [rjmalves/sintetizador-newave#2]
Nas linhas 178:191 do arquivo ```sintetizador-newave/tree/main/sintetizador/adapters/repository/files.py```

```
        (
            Variable.ENERGIA_ARMAZENADA_ABSOLUTA,
            SpatialResolution.RESERVATORIO_EQUIVALENTE,
            TemporalResolution.MES,
        ): lambda dir, ree=1: Earmf.le_arquivo(
            dir, f"earmfm{str(ree).zfill(3)}.out"
        ).valores,
        (
            Variable.ENERGIA_ARMAZENADA_ABSOLUTA,
            SpatialResolution.SUBMERCADO,
            TemporalResolution.MES,
        ): lambda dir, submercado=1: Earmfm.le_arquivo(
            dir, f"earmfm{str(submercado).zfill(3)}.out"
        ).valores
```

A classe para leitura do EARM por REE esta certa, mas o argumento ```nome_arquivo``` esta sendo montado com ```earmfm```, que corresponde a submercados. Por acaso existem submercados com os mesmos nomes de alguns REEs e não da problema, mas na leitura das saídas acabam vindo só quatro REEs (Sul, Sudeste, Norte e Nordeste).

**Comment by rjmalves** [comment]
Foi resolvido no commit 2d0a286be488f217e4d9ae4b86767689b072b75b
