### ISSUE TITLE
Transformação VDEFMIN_UHE_PAT para VDEFMIN_UHE_EST

### ISSUE THREAD

**Issue by davidAlexander08** [rjmalves/sintetizador-newave#24]
![imagem (2)](https://github.com/rjmalves/sintetizador-newave/assets/142263303/02c6942e-1116-46bc-8079-7509515f7ecd)

arquivo VDEFMIN_UHE_EST, conversão de VDEFMIN_UHE_PAT para VDEFMIN_UHE_EST parece não estar batendo. Excel da extrema esquerda mostra o valor do VDEF_UHE_EST para o estágio 10 cenário 10 e o VDEF_UHE_PAT (excel da direita) apresenta valores para patamares do VDEF_UHE_PAT em m3/s. A conta mostra que ao multiplicar-los por 2.63, transformando para hm3 encontram-se os valores:

0, 1360.7 e 2902.01, que somados (pois são hm3, pode somar), resulta em 4262.71, que transformado para m3/s vira 1620.802, não batendo com o valore dado no VDEFMIN_UHE_EST no excel da esquerda.

**Comment by rjmalves** [comment]
A partir do commit 1a7e376e70081a4fda402d2b9b0105e02c3e81e3 os valores de violações estão válidos. Porém, esta e outras violações de variáveis a nível de UHEs passaram a ser disponibilizadas em `hm3` ao invés de `m3/s`.

A partir da release v2.0.0 esta informação poderá ser extraída em ambas as unidades, nos novos formatos das sínteses.
